[package]
name = "solana-zk-token-sdk"
description = "Solana Zk Token SDK"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
version = "1.15.2"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.13"
bytemuck = { version = "1.11.0", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
solana-program = { path = "../sdk/program", version = "=1.15.2" }

[target.'cfg(not(target_os = "solana"))'.dependencies]
aes-gcm-siv = {git="https://github.com/switchboard-xyz/AEADs.git"}
arrayref = "0.3.6"
bincode = "1"
byteorder = "1"
cipher = "0.4"
curve25519-dalek = { git="https://github.com/switchboard-xyz/sb-curve25519-dalek", branch="3.2.1", features = ["serde"] }
getrandom = { version = "0.1", features = ["dummy"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
merlin = "3"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.9"
solana-sdk = { path = "../sdk", version = "=1.15.2" }
subtle = "2"
thiserror = "1.0"
zeroize = { version = "1.5.3", default-features = false, features = ["zeroize_derive"] }

[lib]
crate-type = ["cdylib", "rlib"]
